language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php:
      - hhvm

before_script:
  - composer install

env:
  - LIQUID_PARSER_MODE=lax

script: phpunit --configuration tests/phpunit.xml tests
